In [ ]:
                                Neural Networks & Deep Learning - ICP3

In [7]:
# Question 1

class Employee:
    num_employees = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.num_employees += 1

    @staticmethod
    def average_salary(employees):
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees)

class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, experience):
        super().__init__(name, family, salary, department)
        self.experience = experience

employee1 = Employee("John Doe", "Family A", 60000, "HR")
employee2 = Employee("Jane Smith", "Family B", 75000, "Finance")

fulltime_employee1 = FulltimeEmployee("Alice Johnson", "Family C", 80000, "IT", 3)
fulltime_employee2 = FulltimeEmployee("Bob Williams", "Family D", 90000, "Engineering", 5)

employees = [employee1, employee2, fulltime_employee1, fulltime_employee2]
avg_salary = Employee.average_salary(employees)

print("Average salary:", avg_salary)
print("Total number of employees:", Employee.num_employees)

Average salary: 76250.0
Total number of employees: 4


In [8]:
#Question 2 

import numpy as np
random_vector = np.random.uniform(1, 20, size=20)
print("Original array:")
print(random_vector)

reshaped_array = random_vector.reshape(4, 5)

max_indices = np.argmax(reshaped_array, axis=1)

reshaped_array[np.arange(4), max_indices] = 0

print("\nReshaped array:")
print(reshaped_array)

Original array:
[12.46456192  3.69062693  5.2142561  14.73363379 10.00718565  7.9762804
  3.19262257 17.86598714 11.35888827  5.01449712 12.40118574 15.7919122
 17.14824145 12.84570487  7.41636457  2.21262812  7.23344263  7.87722674
 18.65313592 14.96393701]

Reshaped array:
[[12.46456192  3.69062693  5.2142561   0.         10.00718565]
 [ 7.9762804   3.19262257  0.         11.35888827  5.01449712]
 [12.40118574 15.7919122   0.         12.84570487  7.41636457]
 [ 2.21262812  7.23344263  7.87722674  0.         14.96393701]]
